In [2]:
import numpy as np 
x           = np.array([[1.,2.,3.],[4.,5.,6.]])
size_x      = x.shape

y           = np.array([[10.,20.,30.],[40.,50.,60.]])
size_y      = y.shape

z           = np.array([2.])
size_z      = z.shape

In [3]:
x+y

array([[11., 22., 33.],
       [44., 55., 66.]])

In [4]:
x-z

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [5]:
np.add(x,y)

array([[11., 22., 33.],
       [44., 55., 66.]])

In [ ]:
np.multiply(x,z)

In [6]:
A       = np.array([[1.,2.],[3.,4.],[5.,6.]])
size_A  = A.shape

x       = x = np.array([[10.],[20.]])
size_x  = x.shape

In [8]:
np.dot(A,x)

array([[ 50.],
       [110.],
       [170.]])

In [9]:
A       = np.array([[1.,2.],[3.,4.],[5.,6.]])
size_A  = A.shape

X     = np.array([[10.,20.],[30.,40.]]) 
size_X  = X.shape

Y       = np.dot(A,X)
size_Y  = Y.shape

In [11]:
size_Y

(2, 2)

In [12]:
A                   = np.array([[1.,2.],[3.,4.]])
size_A              = A.shape

AT                  = np.transpose(A)
size_AT             = AT.shape


In [13]:
AT

array([[1., 3.],
       [2., 4.]])

In [14]:
np.dot(AT,A)

array([[10., 14.],
       [14., 20.]])

In [17]:
 np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])